algoritmo "Exercicio4"
var N1, N2, Result: inteiro

inicio
      Escreva("Digite o primeiro número para a soma: ")
      Leia (N1)
      Escreva("Digite o segundo número para a soma: ")
      Leia (N2)
      Result <- (N1 + N2)
      Escreval("-------------------------------------------")
      Escreval("O valor da soma entre", N1, " e ",N2, " é = ", Result)
      Escreval("-------------------------------------------")
fimalgoritmo