algoritmo "Multiplicadora"
var N1, N2, resultado: inteiro
nome: caractere

inicio

 escreva (" Qual seu nome? ")
 leia (nome)
 escreva (nome, " É um belo nome, agora que tal nós efetuarmos uma conta de multiplicação? ", nome, " Me diz um número que você queira multiplicar ")
 leia (N1)
 escreva ("Muito bem ", nome, " agora me fala por qual número você quer multiplicá-lo ")
 leia (N2)
 resultado <- (N1 * N2)
 escreva ("O resultado de ", N1, " vezes ", N2, " é igual a ", resultado)
 
fimalgoritmo